# Generated by Django 4.0.4 on 2022-05-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupedemetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registre', models.CharField(max_length=100)),
                ('sous_registre', models.CharField(max_length=100)),
                ('nom_du_groupe', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('annee_de_creation', models.DateField(blank=True, null=True)),
                ('nombre_album', models.IntegerField()),
                ('courte_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
